import { Command, type Item, type Path } from "@owlbear-rodeo/sdk";
import { describe, expect, it } from "vitest";
import { deriveDoorStrokeColor } from "./colors";
import { applyGeneratedDoorUpdate } from "./createGeneratedDoor";
import { generateDoorGeometry } from "./geometry";
import { parseGeneratedDoorSpec, readGeneratedDoorSpec, writeGeneratedDoorSpec } from "./metadata";
import { getDoorDetailMetrics } from "./metrics";
import { absorbScaleIntoSpec, reconcileGeneratedDoorItem } from "./reconcileGeneratedDoorScale";
import { pathCommandsToSvgD } from "./svgPreview";
import { DEFAULT_GENERATED_DOOR_SPEC, type GeneratedDoorSpec } from "./types";

const dpi = 100;
const base = (overrides: Partial<GeneratedDoorSpec> = {}): GeneratedDoorSpec => ({ version: 1, type: "swing", leaves: "single", style: "plain", width: 100, thickness: 16, color: "#8b5a2b", hingeSide: "left", openAngle: 0, placementRotation: 0, ...overrides });
const points = (spec: GeneratedDoorSpec) => generateDoorGeometry(spec, { dpi }).commands.flatMap((command) => command.slice(1)).filter((value): value is number => typeof value === "number");

describe("generated door geometry", () => {
  it("defaults to one grid cell wide, quarter-cell thick, and ninety degrees open", () => { expect(DEFAULT_GENERATED_DOOR_SPEC).toMatchObject({ width: 100, thickness: 25, openAngle: 90 }); });
  it("generates a valid nonempty single swing path", () => { const value = generateDoorGeometry(base(), { dpi }); expect(value.commands.length).toBeGreaterThan(4); expect(value.commands.some((c) => c[0] === Command.CLOSE)).toBe(true); });
  it("renders both double-swing leaves in one command set", () => { const commands = generateDoorGeometry(base({ leaves: "double" }), { dpi }).commands; expect(commands.filter((c) => c[0] === Command.CLOSE).length).toBeGreaterThanOrEqual(4); });
  it("opens both double-swing leaves in the same direction", () => { const coordinates = points(base({ leaves: "double", openAngle: 90 })); const ys = coordinates.filter((_, index) => index % 2 === 1); expect(Math.max(...ys)).toBeGreaterThan(40); expect(Math.min(...ys)).toBeGreaterThan(-10); });
  it("keeps sliding geometry free of hinge circles", () => { const slide = generateDoorGeometry(base({ type: "slide" }), { dpi }).commands; expect(slide.some((command) => command[0] === Command.CUBIC)).toBe(false); });
  it("uses trap depth independently of width", () => { const shallow = points(base({ type: "trap", depth: 40 })); const deep = points(base({ type: "trap", depth: 90 })); expect(Math.max(...deep.filter((_, i) => i % 2))).toBeGreaterThan(Math.max(...shallow.filter((_, i) => i % 2))); });
  it("mirrors left and right hinge placement", () => { const left = points(base({ hingeSide: "left" })); const right = points(base({ hingeSide: "right" })); expect(Math.min(...left)).toBeCloseTo(-Math.max(...right), 3); });
  it("changes leaf position between zero and ninety degrees", () => { expect(points(base({ openAngle: 0 }))).not.toEqual(points(base({ openAngle: 90 }))); const ninety = points(base({ openAngle: 90 })); expect(Math.max(...ninety)).toBeGreaterThan(80); });
  it("supports swing angles through 135 degrees", () => { expect(points(base({ openAngle: 135 }))).not.toEqual(points(base({ openAngle: 90 }))); });
  it("uses a full-thickness hinge circle centered on the pivot", () => { const commands = generateDoorGeometry(base({ thickness: 20 }), { dpi }).commands; const hingeMove = commands[5]; expect(hingeMove).toEqual([Command.MOVE, -40, 0]); });
  it("starts the swing slab at the hinge tangent instead of overlapping its fill", () => { const commands = generateDoorGeometry(base({ thickness: 20, openAngle: 0 }), { dpi }).commands; expect(commands[0]).toEqual([Command.MOVE, -40, 10]); expect(commands[5]).toEqual([Command.MOVE, -40, 0]); });
  it("uses nonzero filling so overlapping hardware remains opaque", () => { expect(generateDoorGeometry(base({ showKnob: true }), { dpi }).fillRule).toBe("nonzero"); });
  it("keeps the compact line-and-circle hinge language on trap doors", () => { const commands = generateDoorGeometry(base({ type: "trap", depth: 100 }), { dpi }).commands; const hingeLines = commands.filter((command) => command[0] === Command.LINE); expect(hingeLines.length).toBeGreaterThan(4); });
  it("only emits swing knobs when requested", () => { expect(generateDoorGeometry(base({ showKnob: true }), { dpi }).commands.length).toBeGreaterThan(generateDoorGeometry(base({ showKnob: false }), { dpi }).commands.length); });
  it("keeps swing knobs inset from the latch edge", () => { const knobbed = points(base({ showKnob: true, openAngle: 0 })); expect(Math.max(...knobbed)).toBeLessThanOrEqual(60); });
  it("slides a single leaf away and separates double leaves when open", () => { for (const leaves of ["single", "double"] as const) expect(generateDoorGeometry(base({ type: "slide", leaves }), { dpi, open: true }).commands).not.toEqual(generateDoorGeometry(base({ type: "slide", leaves }), { dpi, open: false }).commands); });
  it("renders pocket doors as small jamb-adjacent stubs when open", () => { const pocket = points(base({ type: "pocket" })); const openPocket = generateDoorGeometry(base({ type: "pocket" }), { dpi, open: true }).commands.flatMap((command) => command.slice(1)).filter((value): value is number => typeof value === "number"); const openPlain = generateDoorGeometry(base({ type: "slide" }), { dpi, open: true }).commands.flatMap((command) => command.slice(1)).filter((value): value is number => typeof value === "number"); expect(openPocket).not.toEqual(pocket); expect(Math.max(...openPocket)).toBeLessThan(Math.max(...openPlain)); });
  it("does not add a separate track line to pocket doors", () => { const pocket = generateDoorGeometry(base({ type: "pocket" }), { dpi }).commands; const slide = generateDoorGeometry(base({ type: "slide" }), { dpi }).commands; expect(pocket.length).toBeLessThan(slide.length); });
  it("uses a line handle rather than a circular knob on trap doors", () => { const without = generateDoorGeometry(base({ type: "trap", depth: 100, showKnob: false }), { dpi }).commands; const withHandle = generateDoorGeometry(base({ type: "trap", depth: 100, showKnob: true }), { dpi }).commands; expect(withHandle.length - without.length).toBe(2); expect(withHandle.filter((command) => command[0] === Command.CUBIC).length).toBe(without.filter((command) => command[0] === Command.CUBIC).length); });
  it("renders an open trap as a framed opening with its leaf on edge", () => { const spec = base({ type: "trap", depth: 100, showKnob: true }); const closed = generateDoorGeometry(spec, { dpi, open: false }).commands; const open = generateDoorGeometry(spec, { dpi, open: true }).commands; expect(open).not.toEqual(closed); expect(open.filter((command) => command[0] === Command.CLOSE).length).toBeGreaterThan(closed.filter((command) => command[0] === Command.CLOSE).length); });
  it("renders double traps as two leaves without changing their orientation", () => { const spec = base({ type: "trap", leaves: "double", depth: 100 }); const closed = generateDoorGeometry(spec, { dpi, open: false }).commands; const open = generateDoorGeometry(spec, { dpi, open: true }).commands; expect(closed.some((command, index) => command[0] === Command.MOVE && command[2] === 0 && closed[index + 1]?.[0] === Command.LINE && closed[index + 1]?.[2] === 0)).toBe(true); expect(open.filter((command) => command[0] === Command.CLOSE).length).toBeGreaterThanOrEqual(7); });
  it("gives a one-grid trap three planks and supports inset square panels", () => { const plain = generateDoorGeometry(base({ type: "trap", width: dpi, depth: 100, style: "plain" }), { dpi }).commands; const planked = generateDoorGeometry(base({ type: "trap", width: dpi, depth: 100, style: "planked" }), { dpi }).commands; const paneled = generateDoorGeometry(base({ type: "trap", depth: 100, style: "paneled" }), { dpi }).commands; expect(planked.length - plain.length).toBe(4); expect(paneled.some((command) => command[0] === Command.QUAD)).toBe(true); });
  it("does not scale fixed hardware proportionally with width", () => { const a = getDoorDetailMetrics(base({ width: 100 }), dpi); const b = getDoorDetailMetrics(base({ width: 900 }), dpi); expect(b.handleSize).toBe(a.handleSize); expect(b.hingeSize).toBe(a.hingeSize); });
  it("adds repeated planks as width grows", () => { const narrow = generateDoorGeometry(base({ style: "planked", width: 100 }), { dpi }).commands.length; const wide = generateDoorGeometry(base({ style: "planked", width: 400 }), { dpi }).commands.length; expect(wide).toBeGreaterThan(narrow); });
  it("changes thickness-dependent metrics", () => { expect(getDoorDetailMetrics(base({ thickness: 8 }), dpi).strokeWidth).toBeLessThan(getDoorDetailMetrics(base({ thickness: 35 }), dpi).strokeWidth); });
  it("derives colors deterministically", () => { expect(deriveDoorStrokeColor("#abcdef")).toBe(deriveDoorStrokeColor("#abcdef")); expect(deriveDoorStrokeColor("#abcdef")).not.toBe("#abcdef"); });
  it("converts every emitted command type to SVG", () => { for (const type of ["swing", "slide", "pocket", "trap"] as const) for (const leaves of ["single", "double"] as const) { const d = pathCommandsToSvgD(generateDoorGeometry(base({ type, leaves, ...(type === "trap" ? { depth: 80 } : {}) }), { dpi }).commands); expect(d).toMatch(/^M/); expect(d).toContain("Z"); } });
});

describe("generated door canonical state", () => {
  it("absorbs normal scale into width/thickness", () => { const next = absorbScaleIntoSpec(base(), { x: 2, y: -3 }, dpi); expect(next.width).toBe(200); expect(next.thickness).toBe(48); });
  it("absorbs trap scale into width/depth and permits a 1/1 resting state", () => { const next = absorbScaleIntoSpec(base({ type: "trap", depth: 60 }), { x: -2, y: .5 }, dpi); expect(next.width).toBe(200); expect(next.depth).toBe(30); });
  it("regenerates scaled generated doors into canonical dimensions and resets scale", () => { const item = { id: "resized", type: "PATH", metadata: {}, commands: [], style: { fillColor: "#000", fillOpacity: 1, strokeColor: "#000", strokeOpacity: 1, strokeWidth: 1, strokeDash: [] }, fillRule: "nonzero", scale: { x: 2, y: 1.5 }, name: "old" } as unknown as Path; writeGeneratedDoorSpec(item, base({ width: 100, thickness: 20 })); expect(reconcileGeneratedDoorItem(item, dpi)).toBe(true); expect(readGeneratedDoorSpec(item)).toMatchObject({ width: 200, thickness: 30 }); expect(item.scale).toEqual({ x: 1, y: 1 }); expect(reconcileGeneratedDoorItem(item, dpi)).toBe(false); });
  it("preserves item identity and unrelated metadata during edit", () => { const item = { id: "stable-id", type: "PATH", metadata: { "other/extension": { keep: true } }, commands: [], style: { fillColor: "#000", fillOpacity: 1, strokeColor: "#000", strokeOpacity: 1, strokeWidth: 1, strokeDash: [] }, fillRule: "nonzero", scale: { x: 2, y: 2 }, name: "old" } as unknown as Path; expect(applyGeneratedDoorUpdate(item, base({ color: "#123456" }), dpi)).toBe(true); expect(item.id).toBe("stable-id"); expect(item.metadata["other/extension"]).toEqual({ keep: true }); expect(item.scale).toEqual({ x: 1, y: 1 }); });
  it("reads only versioned generated metadata and leaves ordinary doors unaffected", () => { const ordinary = { metadata: { "other": true } } as unknown as Item; expect(readGeneratedDoorSpec(ordinary)).toBeNull(); writeGeneratedDoorSpec(ordinary, base()); expect(readGeneratedDoorSpec(ordinary)).toEqual(base()); expect(ordinary.metadata.other).toBe(true); });
  it("migrates legacy combined type names into mechanism and leaves axes", () => { expect(parseGeneratedDoorSpec({ ...base(), type: "double-slide", leaves: undefined })).toMatchObject({ type: "slide", leaves: "double" }); expect(parseGeneratedDoorSpec({ ...base(), type: "single-slide", style: "pocket", leaves: undefined })).toMatchObject({ type: "pocket", leaves: "single", style: "plain" }); });
});
